POST http://localhost:3004/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YWMwMDQwMzdkMmU2ZGVlZWY0Yjc5MyIsInVzZXJuYW1lIjoiZmVsaXBlIiwiaWF0IjoxNzIyODg1MTcyfQ.U47o8Bm8-eNkKacU1FaKrUvxEiTLhXz0-R1MHr3WXlw

{
  "content": "let's go to the match"
}